sonar.projectKey=RicsonMiranda_java-for-everybody
sonar.organization=ricsonmiranda
sonar.host.url=https://sonarcloud.io

# Diretório onde está o código-fonte
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8
